name: Build and Deploy Al-Folio Site

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # match your local version
          bundler-cache: true

      # 3. Install ImageMagick (required by jekyll-picture-tag)
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      # 4. Install dependencies via Bundler
      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      # 5. Build the Jekyll site
      - name: Build site
        run: bundle exec jekyll build

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
